### ISSUE TITLE
Destination history of a Trip

### ISSUE THREAD

**Issue by jadmalek** [amawai/android-wikipedia-390#56] opened 2018-03-13 14:21 UTC
The history of destinations selected for a trip by a user is to be created and displayed as part of the trip planner flow. 

Task of US #26 and now pushed to US #70.

- [x] Create database for destination history
- [x] Create destination history UI
- [x] Implement CRUD functionality for destination history
- [x] Implement Unit/UI Test(s)

[Story Points: 3]
[Risk: Medium]
[Priority: Medium]

**Comment by sophiaquach16** [comment] 2018-03-16 14:20
Would have been closed by PR #66, but, due to issues encountered in implementing a new search history database and integrating these additions into the new workflow (set up in PR #64), this task was not completed during Release 2. In actuality, this task was always considered to be additional functionality that would have elevated the look of the feature and improved user experience. Nevertheless, while a trip's destination history was not added in Release 2, it has been added in Sprint 6 (#70), along with a few other augmentations, to finalize this feature.

**Comment by abhandal** [comment] 2018-04-10 03:42
Adding update function to destination history is redundant as the user can select a new destination by performing a search or delete the history from the list. As such, the update feature has been removed from destination history.

**Comment by amawai** [comment] 2018-04-14 07:19
**Acceptance Testing** 

These acceptance tests characterize the expected behavior the task was meant to exhibit. See explanation below for its exclusion from the enhancement of our trip planner feature (#26). 

| Test #         | Inputs | Expected Output  | Status |
| ------------------ | ------------- | ------------- | ------------- |
| 1. Plan a Trip card appears on application's main page.  | Wikipedia application launched.  | A card for the trip planner is displayed, along with the other cards, on the main page.  | PASS  |
| 2. Plan a Trip page display.  | Press on Plan a Trip arrow icon on card.  | The Plan a Trip page is depicted, including a list of trips and the option to plan a new trip.   | PASS  |
| 3. Destination picker display.  | Press on the "+ Plan a new trip" button. | Destinations page is depicted, including a search bar for a destination to be inputted.   | PASS  |
| 4. Particular destination selection.  | Type in the name of the destination and select on the dropdown menu, or simply click on the dropdown menu and select a desired destination. | Selected destination will appear in text format within the search bar.   | PASS  |
| 5. Destination trip history.  | In the Plan a Trip Page, select on trip that has previously been planned. | The planned trips destination that was searched for will appear under the search bar.  | PASS  |
| 6. Remove a destination from the search history.  | Select on the destination in the "Destination Search History" and swipe left. | The destination will be removed from the list of destinations in the selected trip. | PASS  |

**Demo Steps**

1. Launch the application.
2. Scroll down the main page until the Plan a Trip card is visible.
3. Press on the Plan a trip arrow icon to view the Plan a Trip screen.
4. Press on the "+ Plan a new trip" button in order to begin planning a new trip.
5. Search for a particular destination by typing in and selecting a destination provided by the search bar.
6. Go back to trip planner's main screen (no need to complete the entire plan for said trip).
7. Select on the edit ("pencil") icon of the trip planned in previous step.
8. Select on the destination in the "Destination Search History" and swipe left.
9. Confirm that destination has been removed from the germane history.

Closed by #107

**Closed as completed by amawai** 2018-04-14 07:19 UTC
Labels: enhancement, test, trip-planning, task
